version: '1'
services:
  audit_log:
    build:
      context: ./audit
    container_name: audit
    ports:
      - 8110

  processing:
    build:
      context: ./processing
    container_name: processing
    expose:
      - 8100

  receiver:
    build:
      context: ./receiver
    container_name: receiver
    expose:
      - 8080

  storage:
    build:
      context: ./storage
    container_name: storage
    expose:
      - 8090