openapi: 3.0.0
servers: []
info:
  description: This is an API for tracking trades of Acme Stock
  version: "1.0.0"
  title: Acme Stock Tracker API
  contact:
    email: peter@acmetrack.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: traders
    description: ACME Purchases and Sales App
  - name: stocktracker
    description: Tracks purchase and sale of Acme Stock
paths:
  /health:
    get:
      summary: returns 200 if service is running.
      operationId: app.health
      description: Return 200
      responses:
        '200':
          description: Healthy and running returns 200
  /acmestock/new:
    post:
      tags:
        - add_new_stock
      summary: adds new stock listing for purchase/sale
      operationId: app.add_new_stock
      description: Adds a new stock to the market
      responses:
        '201':
          description: stock listed successfully
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_stock'
        description: Purchase Info
  /acmestock/sell:
    post:
      tags:
        - sell_order
      summary: process new sell event
      operationId: app.sell_order
      description: Sells stock
      responses:
        '201':
          description: stock sold
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sell_order'
        description: Sale Info
components:
  schemas:
    new_stock:
      type: object
      required:
        - company
        - listing_id
        - total_shares_available
        - share_price
        - listing_date
      properties:
        company:
          type: string
          example: 'Acme Co.'
        listing_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        total_shares_available:
          type: integer
          example: 1000000
        share_price:
          type: number
          example: 100.0
        listing_date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.123Z'
    sell_order:
      type: object
      required:
        - seller_id
        - broker_id
        - amount
        - share_price
        - sale_date
      properties:
        seller_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        broker_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        amount:
          type: integer
          example: 1
        share_price:
          type: number
          example: 100.0
        sale_date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.123Z'